### ISSUE TITLE
Getopt library on Windows

### ISSUE THREAD

**Issue by joto** [mapbox/vtzero#20]
Building/Testing of some of the examples is disabled on Windows because of the missing getopt library. We should figure something out here.

See also https://github.com/mapbox/protozero/issues/84.

**Comment by springmeyer** [comment]
I don't have a strong feeling on this. I'm okay with this being disabled on windows. I'd also be okay with moving to `boost::program_options` as long as the build auto-disabled features if boost is not available (like we do for variant, since it feels ideal to have vtzero easy to build without boost deps).  Refs https://github.com/mapbox/cpp/issues/35
