### ISSUE TITLE
Builder - Make feature id optional

### ISSUE THREAD

**Issue by flippmoke** [mapbox/vtzero#21]
Currently, the constructor of the different feature builder has an id as a field, this will always set a value of `0` for the feature id, even if no feature id is required. I would propose for the id to be set outside the constructor of the feature builders much like properties.

**Comment by joto** [comment]
There are two issues here:

1. *Setting ID in the constructor vs. through an extra call.* Setting the ID in the constructor allows an optimization: The ID will be the first field in the feature allowing quicker check when getting a feature by ID when reading the tile again. If we have an extra method to set the ID, this is much more complicated to handle, because we either have to remember the ID and then stick it on at the end of the feature or we have to impose more rules on the order the methods to add the geometry, properties, and ID need to be called. Are there situations where you don't know the ID when the constructor is called?

2. *Not setting the id field for 0.* The `id` field has the default `0`, so we could just not set it if it has this value. But I have seen code (I think it was in tippecanoe) where there is a check whether the ID was actually set or not when reading a vector tile. This is a bit confusing, especially when considering a possible future move to proto3 where the default is never encoded in the message. It would be no problem here to have two constructors, one with and one without the ID allowing us to have both options. Question is: Do we want to support that? (See also `feature::has_id()`).

**Comment by flippmoke** [comment]
I am fine with the still having the id set in the constructor, but we need to have a non-zero ids as possible I feel as the field is `optional`. I know that we would like to require there to be ids, but setting it to zero by default possible creates multiple features with the same id. I think this is a mistake. 

>so we could just not set it if it has this value

0 is a valid id, we need to make sure this is still possible as well.

**Comment by joto** [comment]
Fixed in 5e1f210.
