### ISSUE TITLE
Repeated LineTo Commands

### ISSUE THREAD

**Issue by flippmoke** [mapbox/vtzero#29]
While I feel indirectly the 2.x version of the spec is clear that you should not have repeated lineTo commands in the case of polygons/linestrings and that you should just have an increased command count -- there was no such restriction on version 1.

https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4343-linestring-geometry-type

Therefore, I wonder if we should adjust the code the [linestring decode](https://github.com/mapbox/vtzero/blob/master/include/vtzero/geometry.hpp#L288) and [polygon decode](https://github.com/mapbox/vtzero/blob/master/include/vtzero/geometry.hpp#L324) to support multiple `lineto` commands as a possibility.

**Comment by flippmoke** [comment]
We would likely need to research to see if there are tiles in the wild that have this, I am worried that there might be at some place. 
/cc @springmeyer

**Comment by springmeyer** [comment]
@flippmoke my gut says we should keep the code as is for now, but flag this as something we'll want to carefully test in production before fully deploying vtzero. If I'm following correctly, you are concerned about this case? https://github.com/mapbox/mapnik-vector-tile/blob/5ed2d7fb8d99b74c26d40c3953c6a9010a408a65/src/vector_tile_geometry_decoder.ipp#L431-L435. If so, perhaps we could build that code (in DEBUG) and run some tests in staging to see if we encounter v1 tiles with this problem.

**Comment by flippmoke** [comment]
@springmeyer exactly -- and I am more concerned when I have seen other encoders in the past as they might have an error in this specifically. I believe at one time the python encoders had exactly this bug (would have to review their code to confirm).

**Comment by joto** [comment]
Here is an idea I just had how we could handle this: When reading the LineTo command, we look ahead `count` numbers to see what the next command after the coordinate bytes is. If that is another `LineTo` we have a special case. We can then either call the callback with `count==0` to indicate that we don't know or do the lookahead again & so on. Doing the lookahead can be done somewhat cheaper than actually decoding those varints, but it is still overhead that must be paid. For small linestrings/rings this is probably not that problematic, because we need to fetch this data into the CPU cache anyway. But for large linestring/rings it could mean we have to load everything from main memory twice.

We could offer two different interfaces: For cases where the user code doesn't use the `count` anyway, we can ignore all of this and just allow multiple `LineTo`s. And for cases where the user needs the `count` we can do the trick explained above. On the other hands this begs the question: Is knowing the `count` so important that we have to go through all this? Do we really save that much using the count for a `reserve()` or so?

**Comment by flippmoke** [comment]
@joto perhaps we could have two different methods for this -- one for v1 tiles one for v2 tiles? Do we ever want to start sending the different versions to the geometry decoders?

**Comment by joto** [comment]
@flippmoke Do we have an idea by now whether this actually happens in real data?

**Comment by flippmoke** [comment]
@joto We currently have no idea if this actually ever occurs still. I think we are fine for now with this design, if we run into problems we can revisit.

**Comment by springmeyer** [comment]
I agree - Our team has been testing vtzero in production at Mapbox and not seen any indication of problems - nor do I see any indication that the mapnik-vector-tile error mentioned above (https://github.com/mapbox/mapnik-vector-tile/blob/5ed2d7fb8d99b74c26d40c3953c6a9010a408a65/src/vector_tile_geometry_decoder.ipp#L431-L435) has ever been triggered. So, I'm going to close this as I don't see any action needed.
