### ISSUE TITLE
Improvements for efficiently adding layers via bytes

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vtzero#3]
An important usecase is appending raw bytes of existing messages.

Currently the `tile_builder` has `add_layer_with_data` which is close to what is needed. However it only accepts an already created `vtzero::layer`. Ideally you could pass in a `vtzero::data_view` (representing a layer) directly if you have one (without needing to createa a `vtzero::layer`).

Also, let's thing about efficiently adding features to layers via bytes. This usecase might sound odd because normally you need to build up layer keys/values based on feature properties. But in certain high performance cases one might want to be able to filter certain features on a layer and keep others (without re-encoding the layer key/values). So, to efficiently we need to be able to append the raw bytes of features to layers.

/cc @joto

**Comment by joto** [comment]
Adding an existing layer in a `data_view` works now. Just call `tile_builder::add_layer(data_view&)`.

After voice discussions with @flippmoke and @springmeyer it seems to me that copying over the key/value tables from an existing tile to a new tile is usually not want we want. Instead we need to be able to recreate those tables efficiently. In the filtering use case we would otherwise create layers that contain too many unused properties. We can revisit this later if we have evidence that the recreation of those tables is too costly.

**Comment by springmeyer** [comment]
> Adding an existing layer in a data_view works now. Just call tile_builder::add_layer(data_view&).

👍 

> In the filtering use case we would otherwise create layers that contain too many unused properties. We can revisit this later if we have evidence that the recreation of those tables is too costly.

Agree, tables really need to be re-created to save the most space. So the question is how to do it as efficiently as possible.
